# Generated by Django 4.2.4 on 2023-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('subject', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=122)),
                ('message', models.CharField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
