# Generated by Django 4.2.4 on 2023-09-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=122)),
                ('date_time', models.CharField(max_length=122)),
            ],
        ),
    ]
